/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.EstudianteControlador;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class Registro extends javax.swing.JFrame {

    String amateria = "Espeñol";        int apSemestre = 0;  int asSemestre = 0;
    String bmateria = "Matemática";     int bpSemestre = 0;  int bsSemestre = 0;
    String cmateria = "Sociales";       int cpSemestre = 0;  int csSemestre = 0;
    String dmateria = "Ingles";         int dpSemestre = 0;  int dsSemestre = 0;
    String emateria = "Informática";    int epSemestre = 0;  int esSemestre = 0;
    
    int aFinal = 0;                    String aCondicion = "";    int contador = 0;
    int bFinal = 0;                    String bCondicion = "";    int cantidadRegistro = 0;
    int cFinal = 0;                    String cCondicion = "";    int cantidadaplazados = 0;
    int dFinal = 0;                    String dCondicion = "";    String condicionFinal = "";
    int eFinal = 0;                    String eCondicion = "";    int id = 0;
    
    String nombre = "";                   int notas [];
    int materiasAplazadas = 0;
    int materiasReprobadas = 0;
    int materiasAprobadas = 0 ;
    
    EstudianteControlador controlador = new EstudianteControlador();
    
    public Registro() {
        
        initComponents();
        
        boolean validacion = false;
        
        while(!validacion){
        String cantidad = JOptionPane.showInputDialog(null, "Enter the number of "
        + " students you want to register",
        JOptionPane.QUESTION_MESSAGE);
        
        try{
        
        this.cantidadRegistro = Integer.parseInt(cantidad);
        if(this.cantidadRegistro > 0){
        JOptionPane.showMessageDialog(null, "Registration quantity: "+this.cantidadRegistro ,"Registration", 
        JOptionPane.INFORMATION_MESSAGE);
         validacion = true;
        break;
        
        } else {
            
        JOptionPane.showMessageDialog(null,"Introduce numeros mayores a 0","Error!",
        JOptionPane.ERROR_MESSAGE);
        validacion = false;
        }
            
        } catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null,"Introduce numeros validos" , "Error!" , 
        JOptionPane.ERROR_MESSAGE);
          
           }
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIespañol = new javax.swing.JTextField();
        txtIIespañol = new javax.swing.JTextField();
        txtfinalespañol = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtImate = new javax.swing.JTextField();
        txtIImate = new javax.swing.JTextField();
        txtfinalmate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtIsociales = new javax.swing.JTextField();
        txtIIsociales = new javax.swing.JTextField();
        txtfinalsociales = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtIingles = new javax.swing.JTextField();
        txtIIingles = new javax.swing.JTextField();
        txtfinalingles = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtIinfo = new javax.swing.JTextField();
        txtIIinfo = new javax.swing.JTextField();
        txtfinalinfo = new javax.swing.JTextField();
        bt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        jPanel1.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Student Information");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("ID");

        txtid.setBackground(java.awt.Color.black);
        txtid.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        txtid.setForeground(java.awt.Color.white);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Name");

        txtnombre.setBackground(java.awt.Color.black);
        txtnombre.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        txtnombre.setForeground(java.awt.Color.white);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-grade-20.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-grade-20.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Scores");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Spanish");

        txtIespañol.setBackground(java.awt.Color.black);
        txtIespañol.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIespañol.setForeground(java.awt.Color.white);

        txtIIespañol.setBackground(java.awt.Color.black);
        txtIIespañol.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIIespañol.setForeground(java.awt.Color.white);

        txtfinalespañol.setEditable(false);
        txtfinalespañol.setBackground(java.awt.Color.black);
        txtfinalespañol.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtfinalespañol.setForeground(java.awt.Color.white);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Final score");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-grade-20.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-grade-20.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setText("Mathematics");

        txtImate.setBackground(java.awt.Color.black);
        txtImate.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        txtImate.setForeground(java.awt.Color.white);

        txtIImate.setBackground(java.awt.Color.black);
        txtIImate.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIImate.setForeground(java.awt.Color.white);

        txtfinalmate.setEditable(false);
        txtfinalmate.setBackground(java.awt.Color.black);
        txtfinalmate.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtfinalmate.setForeground(java.awt.Color.white);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("Social");

        txtIsociales.setBackground(java.awt.Color.black);
        txtIsociales.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIsociales.setForeground(java.awt.Color.white);

        txtIIsociales.setBackground(java.awt.Color.black);
        txtIIsociales.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIIsociales.setForeground(java.awt.Color.white);

        txtfinalsociales.setEditable(false);
        txtfinalsociales.setBackground(java.awt.Color.black);
        txtfinalsociales.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtfinalsociales.setForeground(java.awt.Color.white);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel13.setForeground(java.awt.Color.black);
        jLabel13.setText("English");

        txtIingles.setBackground(java.awt.Color.black);
        txtIingles.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIingles.setForeground(java.awt.Color.white);

        txtIIingles.setBackground(java.awt.Color.black);
        txtIIingles.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIIingles.setForeground(java.awt.Color.white);

        txtfinalingles.setEditable(false);
        txtfinalingles.setBackground(java.awt.Color.black);
        txtfinalingles.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtfinalingles.setForeground(java.awt.Color.white);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel14.setForeground(java.awt.Color.black);
        jLabel14.setText("Computing");

        txtIinfo.setBackground(java.awt.Color.black);
        txtIinfo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIinfo.setForeground(java.awt.Color.white);
        txtIinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIinfoActionPerformed(evt);
            }
        });

        txtIIinfo.setBackground(java.awt.Color.black);
        txtIIinfo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtIIinfo.setForeground(java.awt.Color.white);

        txtfinalinfo.setEditable(false);
        txtfinalinfo.setBackground(java.awt.Color.black);
        txtfinalinfo.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        txtfinalinfo.setForeground(java.awt.Color.white);

        bt.setBackground(java.awt.Color.green);
        bt.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        bt.setForeground(java.awt.Color.black);
        bt.setText("Process");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.red);
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jButton2.setForeground(java.awt.Color.black);
        jButton2.setText("Go back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel15.setForeground(java.awt.Color.black);
        jLabel15.setText("I Semester");

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel16.setForeground(java.awt.Color.black);
        jLabel16.setText("II Semester");

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jButton1.setForeground(java.awt.Color.black);
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(41, 41, 41)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtImate)
                            .addComponent(txtIespañol)
                            .addComponent(txtIsociales)
                            .addComponent(txtIingles))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIIespañol)
                            .addComponent(txtIImate)
                            .addComponent(txtIIsociales)
                            .addComponent(txtIIingles)
                            .addComponent(txtIIinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jButton1))
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfinalmate)
                            .addComponent(txtfinalespañol)
                            .addComponent(txtfinalsociales)
                            .addComponent(txtfinalingles)
                            .addComponent(txtfinalinfo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(26, 26, 26))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel11))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel14))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel1)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel16)))
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIespañol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIIespañol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfinalespañol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtImate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIImate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfinalmate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIsociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtIIsociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfinalsociales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIingles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtIIingles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfinalingles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIIinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfinalinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIinfoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
    this.procesar();
    }
 public void procesar() {     
    try {
        // Verificación de si las cajas de texto tienen valores válidos
        if (txtIespañol.getText().trim().isEmpty() || 
            txtImate.getText().trim().isEmpty() || 
            txtIsociales.getText().trim().isEmpty() || 
            txtIingles.getText().trim().isEmpty() || 
            txtIinfo.getText().trim().isEmpty() || 
            txtIIespañol.getText().trim().isEmpty() || 
            txtIImate.getText().trim().isEmpty() || 
            txtIIsociales.getText().trim().isEmpty() || 
            txtIIingles.getText().trim().isEmpty() || 
            txtIIinfo.getText().trim().isEmpty() || 
            txtid.getText().trim().isEmpty() || 
            txtnombre.getText().trim().isEmpty()) {
            // Mensaje de depuración
            System.out.println("Algunos campos están vacíos o contienen espacios. Revisa los valores ingresados.");
            throw new NullPointerException("Some fields are empty or do not contain valid values");
        }

        // Asignación de notas del I semestre
        int[] primerSemestre = new int[5];
        try {
            primerSemestre[0] = Integer.parseInt(txtIespañol.getText());
            primerSemestre[1] = Integer.parseInt(txtImate.getText());
            primerSemestre[2] = Integer.parseInt(txtIsociales.getText());
            primerSemestre[3] = Integer.parseInt(txtIingles.getText());
            primerSemestre[4] = Integer.parseInt(txtIinfo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numerical values in the I semester grades.", "Format Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si hay un error en la conversión
        }

        // Asignación de notas del II semestre
        int[] segundoSemestre = new int[5];
        try {
            segundoSemestre[0] = Integer.parseInt(txtIIespañol.getText());
            segundoSemestre[1] = Integer.parseInt(txtIImate.getText());
            segundoSemestre[2] = Integer.parseInt(txtIIsociales.getText());
            segundoSemestre[3] = Integer.parseInt(txtIIingles.getText());
            segundoSemestre[4] = Integer.parseInt(txtIIinfo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid numerical values in the II semester grades", "Format Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método si hay un error en la conversión
        }

        // Cálculo de notas finales
        this.notas = new int[5];
        for (int i = 0; i < 5; i++) {
            this.notas[i] = (primerSemestre[i] + segundoSemestre[i]) / 2;
        }

        // Identificación del estudiante
        int id = Integer.parseInt(txtid.getText());
        String nombre = txtnombre.getText();

        // Contadores de materias
        this.materiasAprobadas = 0;
        this.materiasAplazadas = 0;
        this.materiasReprobadas = 0;

        // Evaluación de estado por cada materia
        for (int nota : this.notas) {
            if (nota >= 70) {
                this.materiasAprobadas++;
            } else if (nota >= 60) {
                this.materiasAplazadas++;
            } else {
                this.materiasReprobadas++;
            }
        }

        // Determinación de la condición final
        if (this.materiasReprobadas > 3) {
            this.condicionFinal = "Reprobate";
        } else if (this.materiasAplazadas > 0) {
            this.condicionFinal = "Postponed";
        } else {
            this.condicionFinal = "Approved";
        }

        // Mostrar las notas finales en la interfaz
        txtfinalespañol.setText(String.valueOf(this.notas[0]));
        txtfinalmate.setText(String.valueOf(this.notas[1]));
        txtfinalsociales.setText(String.valueOf(this.notas[2]));
        txtfinalingles.setText(String.valueOf(this.notas[3]));
        txtfinalinfo.setText(String.valueOf(this.notas[4]));

        // Guardar los datos en el controlador
        this.controlador.agregarEstudiante(id, nombre, this.notas, this.condicionFinal);

        // Mensaje de resultado
        JOptionPane.showMessageDialog(null,
            "Approved subjects: " + this.materiasAprobadas + "\n" +
            "Postponed subjects: " + this.materiasAplazadas + "\n" +
            "Failed subjects: " + this.materiasReprobadas + "\n" +
            "Condition: " + this.condicionFinal);

        // Control de cantidad de registros
        this.contador++;
        if (this.contador == this.cantidadRegistro) {
            JOptionPane.showMessageDialog(null, "The number of records was completed", "Information", JOptionPane.INFORMATION_MESSAGE);
            bt.setEnabled(false);
        }

    } catch (NullPointerException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Insufficient information, fill all fields with numerical values", "Error!", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An unexpected error has ocurred", "Error!", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      txtIespañol.setText(null);
      txtIIespañol.setText(null);
      txtImate.setText(null);
      txtIImate.setText(null);
      txtIsociales.setText(null);
      txtIIsociales.setText(null);
      txtIingles.setText(null);
      txtIIingles.setText(null);
      txtIinfo.setText(null);
      txtIIinfo.setText(null);
      txtfinalespañol.setText(null);
      txtfinalmate.setText(null);
      txtfinalsociales.setText(null);
      txtfinalingles.setText(null);
      txtfinalinfo.setText(null);
      txtid.setText(null);
      txtnombre.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIIespañol;
    private javax.swing.JTextField txtIIinfo;
    private javax.swing.JTextField txtIIingles;
    private javax.swing.JTextField txtIImate;
    private javax.swing.JTextField txtIIsociales;
    private javax.swing.JTextField txtIespañol;
    private javax.swing.JTextField txtIinfo;
    private javax.swing.JTextField txtIingles;
    private javax.swing.JTextField txtImate;
    private javax.swing.JTextField txtIsociales;
    private javax.swing.JTextField txtfinalespañol;
    private javax.swing.JTextField txtfinalinfo;
    private javax.swing.JTextField txtfinalingles;
    private javax.swing.JTextField txtfinalmate;
    private javax.swing.JTextField txtfinalsociales;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
